version: 2.1

jobs:
  build-prod:
    docker:
      - image: cimg/node:18.18.2  # Upewnij się, że używasz właściwej wersji Node.js
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "wZOB6T82Um0GO9fKKncHPEC2cEZlMqRLhA5Wdr6FBsw"
      - restore_cache:
          keys:
            - npm-packages-{{ checksum "package-lock.json" }}
            - npm-packages-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: npm-packages-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
      - run:
          name: Install rsync
          command: sudo apt-get update && sudo apt-get install -y rsync
      - run:
          name: Build and upload application
          command: |
            rsync -avz --exclude-from .rsyncIgnore --delete -e "ssh -o StrictHostKeyChecking=no -i ${SSH_KEY_PATH}" ./ ${MYDEVIL_USER}@${MYDEVIL_HOST}:/home/${MYDEVIL_USER}/domains/liga-q3.pl/public_nodejs/
      - run:
          name: Install pm2 on the server
          command: ssh -o StrictHostKeyChecking=no -i ${SSH_KEY_PATH} ${MYDEVIL_USER}@${MYDEVIL_HOST} "sudo npm install -g pm2"
      - run:
          name: Restart application with pm2
          command: ssh -o StrictHostKeyChecking=no -i ${SSH_KEY_PATH} ${MYDEVIL_USER}@${MYDEVIL_HOST} "cd /home/${MYDEVIL_USER}/domains/liga-q3.pl/public_nodejs && pm2 start ecosystem.config.js --env production"

    environment:
      MYDEVIL_USER: webartstudio
      MYDEVIL_HOST: s49.mydevil.net
      SSH_KEY_PATH: ~/.ssh/id_rsa

workflows:
  build_and_deploy:
    jobs:
      - build-prod:
          filters:
            branches:
              only: main
